### ISSUE TITLE
Open registry links in a new window

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-ai#28] opened 2023-05-12 20:57 UTC
Minor usability feedback: It would be better to open registry links in the chat's response in a new window/tab. As soon as you navigate away, it resets your chat which, especially without history, is a bit unfortunate.

**Comment by AaronFriel** [comment] 2023-09-10 23:50
Closing as a duplicate of #24 - I think we need to apply this to all of the links generated in the response.

**Closed** 2023-09-10 23:50 UTC
Labels: kind/enhancement, resolution/duplicate
