### ISSUE TITLE
yaml programs print out with list styles instead of code styles

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-ai#15] opened 2023-04-14 11:28 UTC
it looks like we are applying some list styles to the output of yaml programs and not code styles
![Screen Shot 2023-04-14 at 4 27 19 AM](https://user-images.githubusercontent.com/5489125/232032023-d3cf6d6a-ca77-4fc5-8ff4-a7a8096db33c.png)

**Comment by lukehoban** [comment] 2023-04-17 01:47
I cannot reproduce this, and I suspect it is not in general reproducible.  But `yaml` support is indeed a fair bit less reliable currently because there is less training data on this format.  I'll close this out, but we will want to look into improved YAML support generally.

**Closed by lukehoban** 2023-04-17 01:47 UTC
Labels: kind/bug, resolution/no-repro

**Comment by susanev** [comment] 2023-04-17 02:13
hmm, i cannot repro now either, i wonder what my question was.
